import type { FloorplanObjectType } from '@/types/database'

// Object template definitions for the palette
export interface ObjectTemplate {
  type: FloorplanObjectType
  label: string
  icon: string
  defaultWidth: number
  defaultHeight: number
  defaultColor: string
  category: 'structures' | 'kitchen' | 'utilities' | 'boundaries' | 'infrastructure' | 'safety' | 'vehicles' | 'annotations'
  description: string
  defaultProperties: Record<string, unknown>
}

export const OBJECT_TEMPLATES: ObjectTemplate[] = [
  // Structures
  {
    type: 'tent',
    label: 'Tent',
    icon: '⛺',
    defaultWidth: 10,
    defaultHeight: 10,
    defaultColor: '#60a5fa',
    category: 'structures',
    description: 'Camper tent — can be marked reservable',
    defaultProperties: { reservable: true },
  },
  {
    type: 'shade_structure',
    label: 'Shade Structure',
    icon: '⛱️',
    defaultWidth: 10,
    defaultHeight: 10,
    defaultColor: '#93c5fd',
    category: 'structures',
    description: '10×10 shade canopy with corner posts',
    defaultProperties: { background: true },
  },
  {
    type: 'shade_sail',
    label: 'Shade Sail',
    icon: '🪁',
    defaultWidth: 15,
    defaultHeight: 15,
    defaultColor: '#f5f0e6',
    category: 'structures',
    description: 'Adjustable shade sail covering — no posts',
    defaultProperties: { background: true },
  },
  {
    type: 'common_area',
    label: 'Common Area',
    icon: '🏕️',
    defaultWidth: 30,
    defaultHeight: 20,
    defaultColor: '#86efac',
    category: 'structures',
    description: 'Shared gathering space',
    defaultProperties: { capacity: 50 },
  },
  {
    type: 'stage',
    label: 'Stage',
    icon: '🎤',
    defaultWidth: 20,
    defaultHeight: 15,
    defaultColor: '#c084fc',
    category: 'structures',
    description: 'Performance stage area',
    defaultProperties: {},
  },
  {
    type: 'bar',
    label: 'Bar',
    icon: '🍹',
    defaultWidth: 15,
    defaultHeight: 8,
    defaultColor: '#f97316',
    category: 'structures',
    description: 'Bar / drink service area',
    defaultProperties: {},
  },
  {
    type: 'art_car',
    label: 'Art Car',
    icon: '🚗',
    defaultWidth: 20,
    defaultHeight: 8,
    defaultColor: '#f472b6',
    category: 'structures',
    description: 'Art car parking pad',
    defaultProperties: {},
  },
  {
    type: 'table',
    label: 'Table',
    icon: '🪑',
    defaultWidth: 8,
    defaultHeight: 4,
    defaultColor: '#d4a373',
    category: 'structures',
    description: 'Table for seating or serving',
    defaultProperties: {},
  },
  {
    type: 'stairs_ladder',
    label: 'Stairs / Ladder',
    icon: '🪜',
    defaultWidth: 12,
    defaultHeight: 5,
    defaultColor: '#475569',
    category: 'structures',
    description: 'Airplane-style rolling staircase — customizable width, depth, and platform elevation',
    defaultProperties: { elevation_ft: 10 },
  },
  {
    type: 'custom',
    label: 'Custom',
    icon: '✏️',
    defaultWidth: 10,
    defaultHeight: 10,
    defaultColor: '#94a3b8',
    category: 'structures',
    description: 'Custom shape — define your own',
    defaultProperties: {},
  },
  // Kitchen
  {
    type: 'kitchen',
    label: 'Kitchen',
    icon: '🍳',
    defaultWidth: 40,
    defaultHeight: 30,
    defaultColor: '#fbbf24',
    category: 'kitchen',
    description: 'Full kitchen zone — break down into sub-areas',
    defaultProperties: {
      responsibilities: ['Food prep', 'Cooking', 'Service', 'Cleanup'],
    },
  },
  {
    type: 'grill',
    label: 'Grill',
    icon: '🔥',
    defaultWidth: 8,
    defaultHeight: 4,
    defaultColor: '#ef4444',
    category: 'kitchen',
    description: 'Grill station inside kitchen',
    defaultProperties: {
      responsibilities: ['Grilling', 'Temperature monitoring', 'Propane management'],
    },
  },
  {
    type: 'prep_area',
    label: 'Prep Area',
    icon: '🔪',
    defaultWidth: 10,
    defaultHeight: 8,
    defaultColor: '#a3e635',
    category: 'kitchen',
    description: 'Food preparation station',
    defaultProperties: {
      responsibilities: ['Chopping', 'Portioning', 'Sanitation'],
    },
  },
  {
    type: 'service_area',
    label: 'Service Area',
    icon: '🍽️',
    defaultWidth: 12,
    defaultHeight: 6,
    defaultColor: '#22d3ee',
    category: 'kitchen',
    description: 'Food service / distribution point',
    defaultProperties: {
      responsibilities: ['Plating', 'Serving', 'Queue management'],
    },
  },
  {
    type: 'storage',
    label: 'Storage',
    icon: '📦',
    defaultWidth: 10,
    defaultHeight: 8,
    defaultColor: '#a1887f',
    category: 'kitchen',
    description: 'Food / supply storage',
    defaultProperties: {},
  },
  {
    type: 'refrigerated_truck',
    label: 'Refrigerated Truck',
    icon: '🚛',
    defaultWidth: 24,
    defaultHeight: 8,
    defaultColor: '#60a5fa',
    category: 'kitchen',
    description: 'Refrigerated truck for cold storage',
    defaultProperties: {},
  },
  // Utilities
  {
    type: 'porta_potty',
    label: 'Porta Potty',
    icon: '🚻',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#64748b',
    category: 'utilities',
    description: 'Portable toilet unit',
    defaultProperties: {},
  },
  {
    type: 'generator',
    label: 'Generator',
    icon: '⚡',
    defaultWidth: 6,
    defaultHeight: 4,
    defaultColor: '#facc15',
    category: 'utilities',
    description: 'Power generator — place within 20ft of frontage/fire lane',
    defaultProperties: {},
  },
  {
    type: 'water_station',
    label: 'Water Station',
    icon: '💧',
    defaultWidth: 6,
    defaultHeight: 4,
    defaultColor: '#38bdf8',
    category: 'utilities',
    description: 'Water distribution point',
    defaultProperties: {},
  },
  {
    type: 'first_aid',
    label: 'First Aid',
    icon: '🏥',
    defaultWidth: 8,
    defaultHeight: 6,
    defaultColor: '#f87171',
    category: 'utilities',
    description: 'Medical / first aid station',
    defaultProperties: {},
  },
  {
    type: 'fire_pit',
    label: 'Fire Pit',
    icon: '🔥',
    defaultWidth: 8,
    defaultHeight: 8,
    defaultColor: '#fb923c',
    category: 'utilities',
    description: 'Communal fire area — 20ft safety zone',
    defaultProperties: { capacity: 20, safety_radius_ft: 20 },
  },
  {
    type: 'bike_parking',
    label: 'Bike Parking',
    icon: '🚲',
    defaultWidth: 12,
    defaultHeight: 6,
    defaultColor: '#a78bfa',
    category: 'utilities',
    description: 'Bike parking area',
    defaultProperties: {},
  },
  {
    type: 'greywater_tank',
    label: 'GreyWater Tank',
    icon: '🪣',
    defaultWidth: 6,
    defaultHeight: 6,
    defaultColor: '#6b7280',
    category: 'utilities',
    description: 'Grey water collection — needs service access',
    defaultProperties: { needs_pumpout: true },
  },
  {
    type: 'swamp_cooler',
    label: 'Swamp Cooler',
    icon: '❄️',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#67e8f9',
    category: 'utilities',
    description: 'Evaporative swamp cooler unit',
    defaultProperties: {},
  },
  {
    type: 'shower_container',
    label: 'Shower Container',
    icon: '🚿',
    defaultWidth: 10,
    defaultHeight: 8,
    defaultColor: '#7dd3fc',
    category: 'utilities',
    description: 'Shower container unit',
    defaultProperties: {},
  },
  {
    type: 'sink_hose',
    label: 'Sink/Hose',
    icon: '🚰',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#38bdf8',
    category: 'utilities',
    description: 'Sink or hose station',
    defaultProperties: {},
  },
  {
    type: 'trash_receptacle',
    label: 'Trash Receptacle',
    icon: '🗑️',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#6b7280',
    category: 'utilities',
    description: 'Waste bin — keep away from generators/fuel',
    defaultProperties: {},
  },
  // Infrastructure
  {
    type: 'fire_lane',
    label: 'Fire Lane',
    icon: '🚒',
    defaultWidth: 20,
    defaultHeight: 100,
    defaultColor: '#fca5a5',
    category: 'infrastructure',
    description: '20ft-wide fire/service access lane — required if depth >125ft',
    defaultProperties: {},
  },
  {
    type: 'road',
    label: 'Road',
    icon: '🛣️',
    defaultWidth: 30,
    defaultHeight: 150,
    defaultColor: '#d1d5db',
    category: 'infrastructure',
    description: 'Adjacent road/street — place outside camp borders',
    defaultProperties: { road_name: '' },
  },
  {
    type: 'path_of_travel',
    label: 'Path of Travel',
    icon: '🚶',
    defaultWidth: 6,
    defaultHeight: 50,
    defaultColor: '#e5e7eb',
    category: 'infrastructure',
    description: 'Internal pedestrian pathway',
    defaultProperties: {},
  },
  // Safety
  {
    type: 'fuel_storage',
    label: 'Fuel Storage',
    icon: '⛽',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#dc2626',
    category: 'safety',
    description: 'Liquid fuel storage — 10/20/50ft safety zones',
    defaultProperties: { fuel_type: 'liquid', safety_radius_ft: 10 },
  },
  {
    type: 'propane_storage',
    label: 'Propane Storage',
    icon: '🔶',
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: '#ea580c',
    category: 'safety',
    description: 'Propane/LPG storage — 10/20/50ft safety zones',
    defaultProperties: { fuel_type: 'propane', safety_radius_ft: 10 },
  },
  {
    type: 'flame_effect',
    label: 'Flame Effect',
    icon: '🎆',
    defaultWidth: 6,
    defaultHeight: 6,
    defaultColor: '#f59e0b',
    category: 'safety',
    description: 'Fire art/effects — 20ft mandatory clearance zone',
    defaultProperties: { safety_radius_ft: 20 },
  },
  {
    type: 'fire_extinguisher',
    label: 'Fire Extinguisher',
    icon: '🧯',
    defaultWidth: 2,
    defaultHeight: 2,
    defaultColor: '#ef4444',
    category: 'safety',
    description: 'Fire extinguisher — place near kitchen, fuel, generators',
    defaultProperties: { ext_type: 'ABC' },
  },
  // Vehicles
  {
    type: 'vehicle',
    label: 'Vehicle',
    icon: '🚙',
    defaultWidth: 18,
    defaultHeight: 8,
    defaultColor: '#a1a1aa',
    category: 'vehicles',
    description: 'Personal vehicle parking',
    defaultProperties: {},
  },
  {
    type: 'rv',
    label: 'RV / Camper',
    icon: '🏠',
    defaultWidth: 30,
    defaultHeight: 10,
    defaultColor: '#78716c',
    category: 'vehicles',
    description: 'RV/camper — show exhaust direction, pumpout access',
    defaultProperties: { needs_pumpout: false, has_generator: false },
  },
  {
    type: 'pc_container',
    label: 'PC Container',
    icon: '📦',
    defaultWidth: 20,
    defaultHeight: 8,
    defaultColor: '#92400e',
    category: 'vehicles',
    description: 'BRC storage container — include PC# and door direction',
    defaultProperties: { pc_number: '', door_direction: 'south' },
  },
  // Boundaries
  {
    type: 'entrance',
    label: 'Entrance',
    icon: '🚪',
    defaultWidth: 10,
    defaultHeight: 4,
    defaultColor: '#4ade80',
    category: 'boundaries',
    description: 'Camp entrance / exit point',
    defaultProperties: {},
  },
  {
    type: 'fence',
    label: 'Fence',
    icon: '🧱',
    defaultWidth: 30,
    defaultHeight: 2,
    defaultColor: '#78716c',
    category: 'boundaries',
    description: 'Fence / barrier segment',
    defaultProperties: {},
  },
  {
    type: 'sign',
    label: 'Sign',
    icon: '🪧',
    defaultWidth: 4,
    defaultHeight: 2,
    defaultColor: '#fbbf24',
    category: 'boundaries',
    description: 'Camp signage / wayfinding',
    defaultProperties: { sign_text: '' },
  },
  // Annotations
  {
    type: 'distance_marker',
    label: 'Distance Marker',
    icon: '📏',
    defaultWidth: 30,
    defaultHeight: 2,
    defaultColor: '#374151',
    category: 'annotations',
    description: 'Dimension line showing distance between points',
    defaultProperties: { distance_ft: 0, from_label: '', to_label: '' },
  },
  {
    type: 'neighbor_zone',
    label: 'Neighbor Zone',
    icon: '🏘️',
    defaultWidth: 50,
    defaultHeight: 50,
    defaultColor: '#e2e8f0',
    category: 'annotations',
    description: 'Preferred neighbor camp placement area',
    defaultProperties: { neighbor_name: '' },
  },
]

export function getTemplateForType(type: FloorplanObjectType): ObjectTemplate | undefined {
  return OBJECT_TEMPLATES.find(t => t.type === type)
}

export const CATEGORY_LABELS: Record<ObjectTemplate['category'], string> = {
  structures: '🏗️ Structures',
  kitchen: '🍳 Kitchen',
  utilities: '⚙️ Utilities',
  infrastructure: '🚒 Infrastructure',
  safety: '🔥 Safety & Fire',
  vehicles: '🚗 Vehicles',
  boundaries: '🧱 Boundaries',
  annotations: '📏 Annotations',
}
